x-mis-backend-defaults: &mis-backend-defaults
  build: ./docker/images/php-server-8-3
  hostname: mis
  restart: always
  networks:
    - postgres
    - proxy
    - redis

services:
  whoami:
    image: traefik/whoami
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.app.build.test`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"

  
  mis-backend:
    <<: *mis-backend-defaults
    volumes:
      - ./services/backend:/var/www/backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.mis-backend.entrypoints=websecure
      - traefik.http.routers.mis-backend.rule=Host(`mis.${TLD}`)
      - traefik.http.services.mis-backend.loadbalancer.server.port=80


networks:
  proxy:
    name: proxy
    external: True
  postgres:
    name: postgres
    external: True
  redis:
    name: redis
    external: True