services:
  postgres:
    build: ./docker/images/postgres
    container_name: build-postgres
    networks:
      - postgres
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
        - ./db/postregs:/var/lib/postgresql
        - ./db/dumps:/dumps
        - ./logs:/var/log/postgresql/
    ports:
    - "5432:5432"
  redis:
    build: ./docker/images/redis
    container_name: build-redis
    mem_limit: 1024m
    networks:
      - redis
    ports:
        - 6379:6379
    command: ["sh", "-c", "exec redis-server --requirepass \"${REDIS_PASSWORD}\""]

networks:
  postgres:
    name: postgres
    external: True
  redis:
    name: redis
    external: True
  